server:
  port: 8080

spring:
  # 타임리프 파일 수정 시 서버 재시작 없이 바로 적용
  thymeleaf:
    cache: false
  profiles:
    group:
      "local": "local, API-KEY, DB"
    active: local
# Database 설정은 application-db.yml에서 함
  devtools:
    livereload:
      enabled: true  # LiveReload 활성화
    restart:
      enabled: true  # 자동 재시작 활성화
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  messages:
    basename: messages/messages
    
# mybatis 설정
mybatis:
  type-aliases-package: com.winemanager
  #type-aliases:
    #userDto: dev.moviesearch.app.user.domain.UserDto
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    multiple-result-sets-enabled: false
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 500
    default-statement-timeout: 25000